#include <parse/Output.h>

namespace parse {

std::string_view nameString(Token token) {
    switch (token) {
    case Token::LeftParen:
        return "LeftParen";
    case Token::RightParen:
        return "RightParen";
    case Token::LeftSqure:
        return "LeftSqure";
    case Token::RightSqure:
        return "RightSqure";
    case Token::LeftBrace:
        return "LeftBrace";
    case Token::RightBrace:
        return "RightBrace";
    case Token::Exclaim:
        return "Exclaim";
    case Token::Tilde:
        return "Tilde";
    case Token::PlusPlus:
        return "PlusPlus";
    case Token::MinusMinus:
        return "MinusMinus";
    case Token::Plus:
        return "Plus";
    case Token::Minus:
        return "Minus";
    case Token::Star:
        return "Star";
    case Token::Amp:
        return "Amp";
    case Token::Hat:
        return "Hat";
    case Token::Vert:
        return "Vert";
    case Token::Slash:
        return "Slash";
    case Token::Percent:
        return "Percent";
    case Token::LessLess:
        return "LessLess";
    case Token::GreaterGreater:
        return "GreaterGreater";
    case Token::AmpAmp:
        return "AmpAmp";
    case Token::VertVert:
        return "VertVert";
    case Token::ExclaimEqual:
        return "ExclaimEqual";
    case Token::EqualEqual:
        return "EqualEqual";
    case Token::Less:
        return "Less";
    case Token::LessEqual:
        return "LessEqual";
    case Token::Greater:
        return "Greater";
    case Token::GreaterEqual:
        return "GreaterEqual";
    case Token::Equal:
        return "Equal";
    case Token::PlusEqual:
        return "PlusEqual";
    case Token::MinusEqual:
        return "MinusEqual";
    case Token::StarEqual:
        return "StarEqual";
    case Token::AmpEqual:
        return "AmpEqual";
    case Token::HatEqual:
        return "HatEqual";
    case Token::VertEqual:
        return "VertEqual";
    case Token::SlashEqual:
        return "SlashEqual";
    case Token::PercentEqual:
        return "PercentEqual";
    case Token::LessLessEqual:
        return "LessLessEqual";
    case Token::GreaterGreaterEqual:
        return "GreaterGreaterEqual";
    case Token::AmpAmpEqual:
        return "AmpAmpEqual";
    case Token::VertVertEqual:
        return "VertVertEqual";
    case Token::Comma:
        return "Comma";
    case Token::Point:
        return "Point";
    case Token::Colon:
        return "Colon";
    case Token::ColonColon:
        return "ColonColon";
    case Token::SemiColon:
        return "SemiColon";
    case Token::EqualGreater:
        return "EqualGreater";
    case Token::LessEqualGreater:
        return "LessEqualGreater";
    case Token::MinusGreater:
        return "MinusGreater";
    case Token::If:
        return "If";
    case Token::Elif:
        return "Elif";
    case Token::Else:
        return "Else";
    case Token::Match:
        return "Match";
    case Token::For:
        return "For";
    case Token::While:
        return "While";
    case Token::Do:
        return "Do";
    case Token::Return:
        return "Return";
    case Token::Break:
        return "Break";
    case Token::Continue:
        return "Continue";
    case Token::Loop:
        return "Loop";
    case Token::Guard:
        return "Guard";
    case Token::Try:
        return "Try";
    case Token::Catch:
        return "Catch";
    case Token::With:
        return "With";
    case Token::Analysis:
        return "Analysis";
    case Token::Assert:
        return "Assert";
    case Token::Namespace:
        return "Namespace";
    case Token::Struct:
        return "Struct";
    case Token::Trait:
        return "Trait";
    case Token::Object:
        return "Object";
    case Token::Fn:
        return "Fn";
    case Token::Has:
        return "Has";
    case Token::Static:
        return "Static";
    case Token::Incomplete:
        return "Incomplete";
    case Token::Virtual:
        return "Virtual";
    case Token::Template:
        return "Template";
    case Token::Var:
        return "Var";
    case Token::Let:
        return "Let";
    case Token::In:
        return "In";
    case Token::Inout:
        return "Inout";
    case Token::Out:
        return "Out";
    case Token::Forward:
        return "Forward";
    case Token::Assign:
        return "Assign";
    case Token::Porperty:
        return "Porperty";
    case Token::Identifier:
        return "Identifier";
    case Token::Literal:
        return "Literal";
    case Token::EOS:
        return "EOS";
    }
}

std::string_view nameString(State state) {
    switch (state) {
    case State::Expression:
        return "Expression";
    case State::AfterExpression:
        return "AfterExpression";
    case State::CommaAfterExpression:
        return "CommaAfterExpression";
    case State::CommaElse:
        return "CommaElse";
    case State::CheckDesignatedArgument:
        return "CheckDesignatedArgument";
    case State::MaybeDesignatedArgument:
        return "MaybeDesignatedArgument";
    case State::FirstArgumentParen:
        return "FirstArgumentParen";
    case State::FirstArgumentSquare:
        return "FirstArgumentSquare";
    case State::FirstArgumentBrace:
        return "FirstArgumentBrace";
    case State::AccessPunctuation:
        return "AccessPunctuation";
    case State::SingleOrCompoundStatement:
        return "SingleOrCompoundStatement";
    case State::AfterStatement:
        return "AfterStatement";
    case State::Statement:
        return "Statement";
    case State::AfterReturn:
        return "AfterReturn";
    case State::ElseBranch:
        return "ElseBranch";
    case State::CheckVarAfterLet:
        return "CheckVarAfterLet";
    case State::VariableDeclaration:
        return "VariableDeclaration";
    case State::AfterVariableDeclarationId:
        return "AfterVariableDeclarationId";
    case State::AfterParameters:
        return "AfterParameters";
    case State::FirstParameter:
        return "FirstParameter";
    case State::Parameter:
        return "Parameter";
    case State::NoDeclaration:
        return "NoDeclaration";
    case State::NamespaceDeclaration:
        return "NamespaceDeclaration";
    case State::NamespaceDeclarationId:
        return "NamespaceDeclarationId";
    case State::AfterNamespaceDeclarationId:
        return "AfterNamespaceDeclarationId";
    case State::NamespaceDeclarationBody:
        return "NamespaceDeclarationBody";
    case State::TemplatedDeclaration:
        return "TemplatedDeclaration";
    case State::TemplatedDeclarationWithAttributes:
        return "TemplatedDeclarationWithAttributes";
    case State::AfterTemplate:
        return "AfterTemplate";
    case State::AfterTemplateParameters:
        return "AfterTemplateParameters";
    case State::FunctionDeclarationId:
        return "FunctionDeclarationId";
    case State::AfterFunctionDeclarationId:
        return "AfterFunctionDeclarationId";
    case State::AfterFunctionParameters:
        return "AfterFunctionParameters";
    case State::TypeDeclarationId:
        return "TypeDeclarationId";
    case State::AfterTypeDeclarationId:
        return "AfterTypeDeclarationId";
    case State::TypeDeclarationBody:
        return "TypeDeclarationBody";
    case State::MemberDeclaration:
        return "MemberDeclaration";
    case State::AfterStatic:
        return "AfterStatic";
    case State::StaticVariableDeclaration:
        return "StaticVariableDeclaration";
    case State::AfterDeclaration:
        return "AfterDeclaration";
    case State::Error:
        return "Error";
    }
}

}
