#include <parse/Output.h>

namespace parse {

std::string_view nameString(LexerToken token) {
    switch (token) {
    case LexerToken::LeftParen:
        return "LeftParen";
    case LexerToken::RightParen:
        return "RightParen";
    case LexerToken::LeftSqure:
        return "LeftSqure";
    case LexerToken::RightSqure:
        return "RightSqure";
    case LexerToken::LeftBrace:
        return "LeftBrace";
    case LexerToken::RightBrace:
        return "RightBrace";
    case LexerToken::Exclaim:
        return "Exclaim";
    case LexerToken::Tilde:
        return "Tilde";
    case LexerToken::PlusPlus:
        return "PlusPlus";
    case LexerToken::MinusMinus:
        return "MinusMinus";
    case LexerToken::Plus:
        return "Plus";
    case LexerToken::Minus:
        return "Minus";
    case LexerToken::Star:
        return "Star";
    case LexerToken::Amp:
        return "Amp";
    case LexerToken::Hat:
        return "Hat";
    case LexerToken::Vert:
        return "Vert";
    case LexerToken::Slash:
        return "Slash";
    case LexerToken::Percent:
        return "Percent";
    case LexerToken::LessLess:
        return "LessLess";
    case LexerToken::GreaterGreater:
        return "GreaterGreater";
    case LexerToken::AmpAmp:
        return "AmpAmp";
    case LexerToken::VertVert:
        return "VertVert";
    case LexerToken::ExclaimEqual:
        return "ExclaimEqual";
    case LexerToken::EqualEqual:
        return "EqualEqual";
    case LexerToken::Less:
        return "Less";
    case LexerToken::LessEqual:
        return "LessEqual";
    case LexerToken::Greater:
        return "Greater";
    case LexerToken::GreaterEqual:
        return "GreaterEqual";
    case LexerToken::Equal:
        return "Equal";
    case LexerToken::PlusEqual:
        return "PlusEqual";
    case LexerToken::MinusEqual:
        return "MinusEqual";
    case LexerToken::StarEqual:
        return "StarEqual";
    case LexerToken::AmpEqual:
        return "AmpEqual";
    case LexerToken::HatEqual:
        return "HatEqual";
    case LexerToken::VertEqual:
        return "VertEqual";
    case LexerToken::SlashEqual:
        return "SlashEqual";
    case LexerToken::PercentEqual:
        return "PercentEqual";
    case LexerToken::LessLessEqual:
        return "LessLessEqual";
    case LexerToken::GreaterGreaterEqual:
        return "GreaterGreaterEqual";
    case LexerToken::AmpAmpEqual:
        return "AmpAmpEqual";
    case LexerToken::VertVertEqual:
        return "VertVertEqual";
    case LexerToken::Comma:
        return "Comma";
    case LexerToken::Point:
        return "Point";
    case LexerToken::Colon:
        return "Colon";
    case LexerToken::ColonColon:
        return "ColonColon";
    case LexerToken::SemiColon:
        return "SemiColon";
    case LexerToken::EqualGreater:
        return "EqualGreater";
    case LexerToken::LessEqualGreater:
        return "LessEqualGreater";
    case LexerToken::MinusGreater:
        return "MinusGreater";
    case LexerToken::Analysis:
        return "Analysis";
    case LexerToken::Assert:
        return "Assert";
    case LexerToken::Assign:
        return "Assign";
    case LexerToken::Break:
        return "Break";
    case LexerToken::Catch:
        return "Catch";
    case LexerToken::Continue:
        return "Continue";
    case LexerToken::Destroy:
        return "Destroy";
    case LexerToken::Discard:
        return "Discard";
    case LexerToken::Do:
        return "Do";
    case LexerToken::Elif:
        return "Elif";
    case LexerToken::Else:
        return "Else";
    case LexerToken::Fn:
        return "Fn";
    case LexerToken::For:
        return "For";
    case LexerToken::Forward:
        return "Forward";
    case LexerToken::Guard:
        return "Guard";
    case LexerToken::Has:
        return "Has";
    case LexerToken::If:
        return "If";
    case LexerToken::In:
        return "In";
    case LexerToken::Incomplete:
        return "Incomplete";
    case LexerToken::Inout:
        return "Inout";
    case LexerToken::Let:
        return "Let";
    case LexerToken::Loop:
        return "Loop";
    case LexerToken::Match:
        return "Match";
    case LexerToken::Namespace:
        return "Namespace";
    case LexerToken::Object:
        return "Object";
    case LexerToken::Out:
        return "Out";
    case LexerToken::Property:
        return "Property";
    case LexerToken::Return:
        return "Return";
    case LexerToken::Static:
        return "Static";
    case LexerToken::Struct:
        return "Struct";
    case LexerToken::Template:
        return "Template";
    case LexerToken::Trait:
        return "Trait";
    case LexerToken::Try:
        return "Try";
    case LexerToken::Var:
        return "Var";
    case LexerToken::Virtual:
        return "Virtual";
    case LexerToken::While:
        return "While";
    case LexerToken::With:
        return "With";
    case LexerToken::Identifier:
        return "Identifier";
    case LexerToken::Literal:
        return "Literal";
    case LexerToken::EOS:
        return "EOS";
    default:
        VERIFY_NOT_REACHED();
    }
}

std::string_view nameString(State state) {
    switch (state) {
    case State::Expression:
        return "Expression";
    case State::AfterExpression:
        return "AfterExpression";
    case State::CommaAfterExpression:
        return "CommaAfterExpression";
    case State::CommaElse:
        return "CommaElse";
    case State::CheckDesignatedArgument:
        return "CheckDesignatedArgument";
    case State::MaybeDesignatedArgument:
        return "MaybeDesignatedArgument";
    case State::FirstArgumentParen:
        return "FirstArgumentParen";
    case State::FirstArgumentSquare:
        return "FirstArgumentSquare";
    case State::FirstArgumentBrace:
        return "FirstArgumentBrace";
    case State::AccessPunctuation:
        return "AccessPunctuation";
    case State::SingleOrCompoundStatement:
        return "SingleOrCompoundStatement";
    case State::AfterStatement:
        return "AfterStatement";
    case State::Statement:
        return "Statement";
    case State::AfterReturn:
        return "AfterReturn";
    case State::ElseBranch:
        return "ElseBranch";
    case State::CheckVarAfterLet:
        return "CheckVarAfterLet";
    case State::VariableDeclaration:
        return "VariableDeclaration";
    case State::AfterVariableDeclarationId:
        return "AfterVariableDeclarationId";
    case State::AfterParameters:
        return "AfterParameters";
    case State::FirstParameter:
        return "FirstParameter";
    case State::Parameter:
        return "Parameter";
    case State::NoDeclaration:
        return "NoDeclaration";
    case State::NamespaceDeclaration:
        return "NamespaceDeclaration";
    case State::NamespaceDeclarationId:
        return "NamespaceDeclarationId";
    case State::AfterNamespaceDeclarationId:
        return "AfterNamespaceDeclarationId";
    case State::NamespaceDeclarationBody:
        return "NamespaceDeclarationBody";
    case State::TemplatedDeclaration:
        return "TemplatedDeclaration";
    case State::TemplatedDeclarationWithAttributes:
        return "TemplatedDeclarationWithAttributes";
    case State::AfterTemplate:
        return "AfterTemplate";
    case State::AfterTemplateParameters:
        return "AfterTemplateParameters";
    case State::FunctionDeclarationId:
        return "FunctionDeclarationId";
    case State::AfterFunctionDeclarationId:
        return "AfterFunctionDeclarationId";
    case State::AfterFunctionParameters:
        return "AfterFunctionParameters";
    case State::TypeDeclarationId:
        return "TypeDeclarationId";
    case State::AfterTypeDeclarationId:
        return "AfterTypeDeclarationId";
    case State::TypeDeclarationBody:
        return "TypeDeclarationBody";
    case State::MemberDeclaration:
        return "MemberDeclaration";
    case State::AfterStatic:
        return "AfterStatic";
    case State::StaticLetVariableDeclaration:
        return "StaticLetVariableDeclaration";
    case State::StaticVarVariableDeclaration:
        return "StaticVarVariableDeclaration";
    case State::AfterDeclaration:
        return "AfterDeclaration";
    case State::Error:
        return "Error";
    default:
        VERIFY_NOT_REACHED();
    }
}

}
